# version: "3.9"

# services:

#   api:
#     build: .
#     container_name: adult-income-api
#     ports:
#       - "8000:8000"
#     restart: unless-stopped

#   dashboard:
#     build: .
#     container_name: adult-income-dashboard
#     command:
#       - streamlit
#       - run
#       - dashboard/app.py
#       - --server.address=0.0.0.0
#       - --server.port=8501
#     ports:
#       - "8501:8501"
#     depends_on:
#       - api
#     restart: unless-stopped





services:

api:
build: .
container_name: adult-income-api
ports:
- "8000:8000"
restart: unless-stopped

dashboard:
build: .
container_name: adult-income-dashboard
command:
- streamlit
- run
- dashboard/app.py
- --server.address=0.0.0.0
- --server.port=8501
environment:
API_URL: http://api:8000
ports:
- "8501:8501"
depends_on:
- api
restart: unless-stopped